// flow-typed signature: 8a011ab5b61f036581c546d98609af71
// flow-typed version: <<STUB>>/jest-jasmine2_v^20.0.4/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-jasmine2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-jasmine2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-jasmine2/build/assert-support' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/ExpectationFailed' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/expectationResultFactory' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/index' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine-async' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/CallTracker' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/createSpy' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/Env' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/jasmine-light' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/JsApiReporter' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/ReportDispatcher' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/Spec' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/SpyRegistry' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/SpyStrategy' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/Suite' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine/Timer' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jest-expect' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/p-timeout' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/queueRunner' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/reporter' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/setup-jest-globals' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/treeProcessor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-jasmine2/build/assert-support.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/assert-support'>;
}
declare module 'jest-jasmine2/build/ExpectationFailed.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/ExpectationFailed'>;
}
declare module 'jest-jasmine2/build/expectationResultFactory.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/expectationResultFactory'>;
}
declare module 'jest-jasmine2/build/index.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/index'>;
}
declare module 'jest-jasmine2/build/jasmine-async.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine-async'>;
}
declare module 'jest-jasmine2/build/jasmine/CallTracker.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/CallTracker'>;
}
declare module 'jest-jasmine2/build/jasmine/createSpy.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/createSpy'>;
}
declare module 'jest-jasmine2/build/jasmine/Env.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/Env'>;
}
declare module 'jest-jasmine2/build/jasmine/jasmine-light.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/jasmine-light'>;
}
declare module 'jest-jasmine2/build/jasmine/JsApiReporter.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/JsApiReporter'>;
}
declare module 'jest-jasmine2/build/jasmine/ReportDispatcher.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/ReportDispatcher'>;
}
declare module 'jest-jasmine2/build/jasmine/Spec.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/Spec'>;
}
declare module 'jest-jasmine2/build/jasmine/SpyRegistry.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/SpyRegistry'>;
}
declare module 'jest-jasmine2/build/jasmine/SpyStrategy.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/SpyStrategy'>;
}
declare module 'jest-jasmine2/build/jasmine/Suite.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/Suite'>;
}
declare module 'jest-jasmine2/build/jasmine/Timer.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine/Timer'>;
}
declare module 'jest-jasmine2/build/jest-expect.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jest-expect'>;
}
declare module 'jest-jasmine2/build/p-timeout.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/p-timeout'>;
}
declare module 'jest-jasmine2/build/queueRunner.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/queueRunner'>;
}
declare module 'jest-jasmine2/build/reporter.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/reporter'>;
}
declare module 'jest-jasmine2/build/setup-jest-globals.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/setup-jest-globals'>;
}
declare module 'jest-jasmine2/build/treeProcessor.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/treeProcessor'>;
}
